# Generated by Django 5.2.5 on 2025-08-22 03:05

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, region='NG', unique=True),
        ),
    ]
