# Generated by Django 5.2.5 on 2025-08-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_options_remove_payment_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='country',
            field=models.CharField(default='NG', max_length=10),
        ),
    ]
